### ISSUE TITLE
registry.cn-beijing.aliyuncs.com 仓库访问不了

### ISSUE THREAD

**Issue by HelloChenHZ** [osswangxining/istio-book#1]
registry.cn-beijing.aliyuncs.com 仓库中镜像拉取不到

**Comment by osswangxining** [comment]
麻烦确认下具体是哪个镜像访问不了，多谢

**Comment by HelloChenHZ** [comment]
比如registry.cn-beijing.aliyuncs.com/wangxining/mirrorservice:latest 这个镜像 我想要拉取到本地
直接拉取拉不到，然后在阿里云上创建账号也拉不到

**Comment by osswangxining** [comment]
docker pull registry.cn-beijing.aliyuncs.com/wangxining/mirrorservice:latest
latest: Pulling from wangxining/mirrorservice
e7c96db7181b: Pull complete
f910a506b6cb: Pull complete
c2274a1a0e27: Downloading [=============================================>     ]   63.8MB/70.73MB
407889154cbe: Download complete
968267edb113: Downloading [============================================>      ]  14.96MB/16.92MB

**Comment by osswangxining** [comment]
> 比如registry.cn-beijing.aliyuncs.com/wangxining/mirrorservice:latest 这个镜像 我想要拉取到本地
> 直接拉取拉不到，然后在阿里云上创建账号也拉不到

这个镜像是公开的，直接docker pull是可以的，如上所示。 anyway， 我也push到dockerhub, 你可以这样获取 docker pull osswangxining/mirrorservice:latest

**Comment by HelloChenHZ** [comment]
是我集群的网络设置问题 可以拉取到
