### ISSUE TITLE
大佬是把书里的镜像源都搞成私有仓库了么

### ISSUE THREAD

**Issue by chonjiang** [osswangxining/istio-book#3]
比如这个：registry.cn-hangzhou.aliyuncs.com/wangxining/curl

**Comment by osswangxining** [comment]
please use this tutum/curl from dockerhub, if you cannot fetch this image because of some IP forbidden.



在 2021-03-26 09:57:42，"jza123" ***@***.***> 写道：

比如这个：registry.cn-hangzhou.aliyuncs.com/wangxining/curl

**Comment by osswangxining** [comment]
if any other images cannot be fetched, please also let me know. thanks a lot!
