### ISSUE TITLE
第一个演示的镜像已经没有了

### ISSUE THREAD

**Issue by thinkdb1** [osswangxining/istio-book#5]
麻烦看一下
`docker pull registry.cn-hangzhou.aliyuncs.com/wangxining/voting-app:1.0`
Error response from daemon: pull access denied for registry.cn-hangzhou.aliyuncs.com/wangxining/voting-app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by osswangxining** [comment]
不知道是否可以访问dockerhub？可以的话, 试下这个osswangxining/voting-app:1.0呢
